# BreachLine infrastructure orchestration.
#
# Single source of truth: config.yml (plaintext, committed) +
# secrets.vault.yml (ansible-vault encrypted, committed). Everything
# downstream (secrets.env, per-component <env>.tfvars) is generated by
# `make render`.
#
# Two environments (dev / prod) coexist in the SAME AWS account: every
# resource name + terraform state key is suffixed with -<env>. dev points at
# the Stripe sandbox, prod at the Stripe live API. Select the target with
# ENV=dev|prod (default dev):
#
#   make init                 # bootstrap config.yml + secrets.vault.yml + pw file
#   make edit-secrets         # set Stripe keys
#   make deploy ENV=dev       # build lambdas + terraform apply the dev stack
#   make deploy-prod          # shorthand for `make deploy ENV=prod`
#
# To move between machines: clone the repo and copy .vault-password-file from
# 1Password, then `make render ENV=<env> && make deploy ENV=<env>`.
# AWS credentials come from the standard chain (env / shared config / SSO).

SHELL := /bin/bash
REPO  := $(shell pwd)
VENV  := $(REPO)/scripts/venv
PY    := $(VENV)/bin/python3

# Target environment. Override per-invocation: `make deploy ENV=prod`.
ENV ?= dev

# Reject anything but dev/prod up front so a typo can't spin up a stray stack.
ENV_GUARD = \
	if [ "$(ENV)" != "dev" ] && [ "$(ENV)" != "prod" ]; then \
	  echo "[error] ENV must be dev or prod (got '$(ENV)')" >&2; exit 1; \
	fi

# Each recipe sources secrets.env so TF_VAR_* are exported into the same shell
# as the terraform command.
SRC := set -a; . $(REPO)/secrets.env; set +a

.PHONY: help venv init render edit-secrets view-secrets edit-config \
        build build-payment-api build-sync-api build-website preview-website \
        tf-payment-api tf-sync-api tf-website \
        tf-payment-api-destroy tf-sync-api-destroy tf-website-destroy \
        enable-website disable-website enable-sync-api disable-sync-api \
        enable-payment-api disable-payment-api \
        deploy destroy all clean \
        deploy-dev deploy-prod destroy-dev destroy-prod

help:  ## @core Show this help
	@awk 'BEGIN { \
	    FS = ":.*?## "; \
	    title[1] = "Core -- config + full pipeline"; \
	    title[2] = "Toggle -- persistent on/off (remembered by deploy)"; \
	    title[3] = "Build -- lambda zips / website"; \
	    title[4] = "Apply -- per-component terraform (honours ENV)"; \
	    title[5] = "Destroy -- per-component teardown (honours ENV)"; \
	    idx["@core"] = 1; idx["@toggle"] = 2; idx["@build"] = 3; idx["@apply"] = 4; idx["@destroy"] = 5; \
	    count[1]=0; count[2]=0; count[3]=0; count[4]=0; count[5]=0; \
	} \
	/^[a-zA-Z0-9_.-]+:.*?## @/ { \
	    desc = $$2; tag = desc; sub(/ .*/, "", tag); sub(/^@[^ ]+ +/, "", desc); \
	    s = idx[tag]; \
	    if (s > 0) { section_target[s, count[s]] = $$1; section_desc[s, count[s]] = desc; count[s]++; } \
	} \
	END { \
	    printf "\nBreachLine infra -- ENV=%s (override with ENV=dev|prod)\n", "'"$(ENV)"'"; \
	    for (s = 1; s <= 5; s++) { \
	        printf "\n\033[1;33m== %s ==\033[0m\n", title[s]; \
	        for (j = 0; j < count[s]; j++) \
	            printf "  \033[36m%-26s\033[0m %s\n", section_target[s, j], section_desc[s, j]; \
	    } \
	    printf "\n"; \
	}' $(MAKEFILE_LIST)

# ==================== Bootstrap / config ====================

venv:  ## @core Create scripts/venv with the render/init dependencies
	@test -d $(VENV) || python3 -m venv $(VENV)
	@$(VENV)/bin/pip install -q -U pip
	@$(VENV)/bin/pip install -q -r $(REPO)/scripts/infra-requirements.txt
	@echo "[ok] venv ready at scripts/venv"

init: venv  ## @core Bootstrap or repair config.yml + secrets.vault.yml + .vault-password-file
	@$(PY) scripts/init.py

edit-secrets:  ## @core Edit the encrypted secrets.vault.yml (only saves if changed)
	@./scripts/edit-secrets.sh

view-secrets:  ## @core View the decrypted secrets.vault.yml (read-only)
	@ansible-vault view --vault-password-file .vault-password-file secrets.vault.yml

edit-config:  ## @core Edit plaintext config.yml in $$EDITOR
	@$${EDITOR:-vi} config.yml

render: venv  ## @core Render secrets.env + infra/*/<ENV>.tfvars for ENV
	@$(ENV_GUARD)
	@$(PY) scripts/render-config.py $(ENV)

# ==================== Component toggles ====================
# Flip the persisted flag in config.yml (so `make deploy` remembers), scoped to
# the ENV's components block, then apply/destroy immediately.

enable-website:  ## @toggle Turn the website ON for ENV (persists) + apply
	@$(ENV_GUARD); ./scripts/set-flag.sh website true $(ENV); $(MAKE) tf-website ENV=$(ENV)

disable-website:  ## @toggle Turn the website OFF for ENV (persists) + destroy
	@$(ENV_GUARD); ./scripts/set-flag.sh website false $(ENV); $(MAKE) tf-website-destroy ENV=$(ENV)

enable-sync-api:  ## @toggle Turn the sync-api ON for ENV (persists) + apply
	@$(ENV_GUARD); ./scripts/set-flag.sh sync_api true $(ENV); $(MAKE) tf-sync-api ENV=$(ENV)

disable-sync-api:  ## @toggle Turn the sync-api OFF for ENV (persists) + destroy
	@$(ENV_GUARD); ./scripts/set-flag.sh sync_api false $(ENV); $(MAKE) tf-sync-api-destroy ENV=$(ENV)

enable-payment-api:  ## @toggle Turn the payment-api ON for ENV (persists) + apply
	@$(ENV_GUARD); ./scripts/set-flag.sh payment_api true $(ENV); $(MAKE) tf-payment-api ENV=$(ENV)

disable-payment-api:  ## @toggle Turn the payment-api OFF for ENV (persists) + destroy
	@$(ENV_GUARD); ./scripts/set-flag.sh payment_api false $(ENV); $(MAKE) tf-payment-api-destroy ENV=$(ENV)

# ==================== Builds ====================

build-payment-api:  ## @build Compile the payment-api Go lambda zips
	@cd infra/payment-api && ./build.sh

build-sync-api:  ## @build Compile the sync-api Go lambda zips
	@cd infra/sync-api && ./build.sh

build-website:  ## @build Build the live website into infra/website/src/public (drafts excluded)
	@cd infra/website/src && hugo --minify --cleanDestinationDir

preview-website:  ## @build Preview the website WITH drafts (live reload) on 0.0.0.0:1313 (LAN-accessible)
	@cd infra/website/src && hugo server -D --bind 0.0.0.0

build: build-payment-api build-sync-api build-website  ## @core Build all lambda zips + the website

# ==================== Terraform applies ====================
# Each renders ENV's config, sources secrets.env (TF_VAR_* secrets), inits the
# S3 backend at the env-scoped state key, and applies the env tfvars.

tf-payment-api: render build-payment-api  ## @apply Apply infra/payment-api for ENV
	@$(ENV_GUARD); $(SRC); cd infra/payment-api && \
	  terraform init -reconfigure -backend-config="key=payment-api/$(ENV)/terraform.tfstate" && \
	  terraform apply -auto-approve -var-file=$(ENV).tfvars

tf-sync-api: render build-sync-api  ## @apply Apply infra/sync-api for ENV
	@$(ENV_GUARD); $(SRC); cd infra/sync-api && \
	  terraform init -reconfigure -backend-config="key=sync-api/$(ENV)/terraform.tfstate" && \
	  terraform apply -auto-approve -var-file=$(ENV).tfvars

tf-website: render build-website  ## @apply Apply infra/website for ENV
	@$(ENV_GUARD); $(SRC); cd infra/website && \
	  terraform init -reconfigure -backend-config="key=website/$(ENV)/terraform.tfstate" && \
	  terraform apply -auto-approve -var-file=$(ENV).tfvars

# ==================== Terraform destroys ====================

tf-payment-api-destroy: render  ## @destroy Destroy infra/payment-api for ENV
	@$(ENV_GUARD); $(SRC); cd infra/payment-api && \
	  terraform init -reconfigure -backend-config="key=payment-api/$(ENV)/terraform.tfstate" && \
	  terraform destroy -auto-approve -var-file=$(ENV).tfvars

tf-sync-api-destroy: render  ## @destroy Destroy infra/sync-api for ENV
	@$(ENV_GUARD); $(SRC); cd infra/sync-api && \
	  terraform init -reconfigure -backend-config="key=sync-api/$(ENV)/terraform.tfstate" && \
	  terraform destroy -auto-approve -var-file=$(ENV).tfvars

tf-website-destroy: render  ## @destroy Destroy infra/website for ENV
	@$(ENV_GUARD); $(SRC); cd infra/website && \
	  terraform init -reconfigure -backend-config="key=website/$(ENV)/terraform.tfstate" && \
	  terraform destroy -auto-approve -var-file=$(ENV).tfvars

# ==================== Full pipeline ====================
# Apply order: payment-api (license signing + Stripe) -> sync-api (validates
# licenses, signs JWTs) -> website. Each honours its component toggle so a
# disabled component is skipped.

deploy: render  ## @core Build + apply every enabled component for ENV
	@$(ENV_GUARD)
	@$(SRC); if [ "$$MAKE_PAYMENT_API_ENABLED" = "true" ]; then \
	    $(MAKE) tf-payment-api ENV=$(ENV); \
	  else echo "[skip] payment-api disabled for $(ENV)"; fi
	@$(SRC); if [ "$$MAKE_SYNC_API_ENABLED" = "true" ]; then \
	    $(MAKE) tf-sync-api ENV=$(ENV); \
	  else echo "[skip] sync-api disabled for $(ENV)"; fi
	@$(SRC); if [ "$$MAKE_WEBSITE_ENABLED" = "true" ]; then \
	    $(MAKE) tf-website ENV=$(ENV); \
	  else echo "[skip] website disabled for $(ENV)"; fi
	@echo "[ok] deploy complete ($(ENV))"

destroy: render  ## @core Destroy every component for ENV (reverse order)
	@$(ENV_GUARD)
	@$(MAKE) tf-website-destroy ENV=$(ENV)
	@$(MAKE) tf-sync-api-destroy ENV=$(ENV)
	@$(MAKE) tf-payment-api-destroy ENV=$(ENV)
	@echo "[ok] destroy complete ($(ENV))"

all: build deploy  ## @core Build everything then deploy (ENV)

# Env-pinned convenience wrappers.
deploy-dev:   ; @$(MAKE) deploy ENV=dev
deploy-prod:  ; @$(MAKE) deploy ENV=prod
destroy-dev:  ; @$(MAKE) destroy ENV=dev
destroy-prod: ; @$(MAKE) destroy ENV=prod

# ==================== Utility ====================

clean:  ## @core Remove rendered files (keeps config.yml + secrets.vault.yml + pw file)
	@rm -f secrets.env
	@find infra -maxdepth 2 -name "dev.tfvars" -delete
	@find infra -maxdepth 2 -name "prod.tfvars" -delete
	@echo "[ok] cleaned rendered files"
