#!/usr/bin/env python3
"""Render secrets.env + per-component Terraform variable files for one
environment (dev|prod) from config.yml + secrets.vault.yml.

Two sources of truth:
  - config.yml         (plaintext, repo root)         - non-secret config
  - secrets.vault.yml  (ansible-vault encrypted)      - secrets only

Both have a top-level wrapper key (config: / vault:) and, below that, an
`environments.<env>` block so dev and prod can carry different values.

Generated files (all gitignored, written 0600):
  - secrets.env                          # TF_VAR_* secret exports, sourced by Make
  - infra/website/<env>.tfvars           # non-secret website config
  - infra/sync-api/<env>.tfvars          # non-secret sync-api config
  - infra/payment-api/<env>.tfvars       # non-secret payment-api config

Run via `make render ENV=<env>`, or directly:
    python3 scripts/render-config.py <env>
"""

import os
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ModuleNotFoundError:
    sys.exit("pyyaml not installed; run `make venv` or `pip install pyyaml`")

REPO = Path(__file__).resolve().parents[1]
CONFIG_FILE = REPO / "config.yml"
VAULT_FILE = REPO / "secrets.vault.yml"
VAULT_PW = REPO / ".vault-password-file"

ENVIRONMENTS = ("dev", "prod")

HEADER = ("# Auto-generated by scripts/render-config.py - do not edit.\n"
          "# Source of truth: config.yml + secrets.vault.yml\n")


def load_config() -> dict:
    if not CONFIG_FILE.exists():
        sys.exit(f"{CONFIG_FILE} not found - run `make init`")
    data = yaml.safe_load(CONFIG_FILE.read_text())
    if not isinstance(data, dict) or "config" not in data:
        sys.exit(f"{CONFIG_FILE} must have a top-level `config:` key")
    return data["config"]


def load_vault() -> dict:
    if not VAULT_FILE.exists():
        sys.exit(f"{VAULT_FILE} not found - run `make init`")
    if not VAULT_PW.exists():
        sys.exit(f"{VAULT_PW} not found - restore from 1Password")
    proc = subprocess.run(
        ["ansible-vault", "view", "--vault-password-file", str(VAULT_PW), str(VAULT_FILE)],
        capture_output=True, text=True, check=False,
    )
    if proc.returncode != 0:
        sys.exit(f"ansible-vault view failed:\n{proc.stderr}")
    data = yaml.safe_load(proc.stdout)
    if not isinstance(data, dict) or "vault" not in data:
        sys.exit(f"{VAULT_FILE} must have a top-level `vault:` key")
    return data["vault"]


def write(path: Path, content: str, mode: int = 0o600) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    os.chmod(path, mode)
    print(f"  wrote {path.relative_to(REPO)}")


def env_component(c: dict, env: str, component: str) -> dict:
    """Return the component config for `env`, with config.defaults.<component>
    merged underneath (the per-env block wins on key collisions)."""
    defaults = (c.get("defaults") or {}).get(component, {}) or {}
    per_env = ((c.get("environments") or {}).get(env) or {}).get(component, {}) or {}
    merged = dict(defaults)
    merged.update(per_env)
    return merged


def env_components_enabled(c: dict, env: str) -> dict:
    return ((c.get("environments") or {}).get(env) or {}).get("components", {}) or {}


def hcl_bool(v) -> str:
    return "true" if v else "false"


def sh_str(s: str) -> str:
    """Escape a value for a bash double-quoted string. PEM/base64/Stripe keys
    contain none of $ ` " \\, but guard anyway."""
    return (str(s).replace("\\", "\\\\").replace("`", "\\`")
            .replace('"', '\\"').replace("$", "\\$"))


# ===== secrets.env (TF_VAR_* secrets, sourced by Make) =====

def render_secrets_env(c: dict, v: dict, env: str) -> None:
    region = c["aws"]["region"]
    ve = ((v.get("environments") or {}).get(env) or {})
    stripe = ve.get("stripe", {}) or {}
    lic = ve.get("license", {}) or {}
    jwt = ve.get("jwt", {}) or {}
    comps = env_components_enabled(c, env)
    body = f"""{HEADER}# Environment: {env}

# ----- Shared -----
export AWS_REGION="{region}"
export BREACHLINE_ENV="{env}"

# ----- payment-api (Stripe + license signing) -----
export TF_VAR_stripe_api_key="{sh_str(stripe.get('api_key', ''))}"
export TF_VAR_stripe_webhook_secret="{sh_str(stripe.get('webhook_secret', ''))}"
export TF_VAR_license_signing_private_key="{sh_str(lic.get('signing_private_key', ''))}"

# ----- sync-api (license validation + JWT signing) -----
export TF_VAR_license_public_key="{sh_str(lic.get('public_key', ''))}"
export TF_VAR_jwt_private_key="{sh_str(jwt.get('private_key', ''))}"
export TF_VAR_jwt_public_key="{sh_str(jwt.get('public_key', ''))}"

# ----- Component toggles (read by the Makefile's `deploy` target) -----
export MAKE_WEBSITE_ENABLED="{hcl_bool(comps.get('website', True))}"
export MAKE_SYNC_API_ENABLED="{hcl_bool(comps.get('sync_api', True))}"
export MAKE_PAYMENT_API_ENABLED="{hcl_bool(comps.get('payment_api', True))}"
"""
    write(REPO / "secrets.env", body)


# ===== per-component <env>.tfvars (non-secret config) =====

def render_website(c: dict, env: str) -> None:
    w = env_component(c, env, "website")
    body = f"""{HEADER}
aws_region          = "{c['aws']['region']}"
environment         = "{env}"
project_name        = "breachline"
domain_name         = "{w.get('domain_name', '')}"
subdomain           = "{w.get('subdomain', '')}"
enable_ssl          = {hcl_bool(w.get('enable_ssl', False))}
price_class         = "{w.get('price_class', 'PriceClass_100')}"
default_root_object = "{w.get('default_root_object', 'index.html')}"
error_document      = "{w.get('error_document', 'error.html')}"
"""
    write(REPO / f"infra/website/{env}.tfvars", body)


def render_sync_api(c: dict, env: str) -> None:
    s = env_component(c, env, "sync_api")
    # license_public_key is sensitive -> comes from secrets.env as TF_VAR_*.
    body = f"""{HEADER}
aws_region             = "{c['aws']['region']}"
environment            = "{env}"
project                = "breachline"
api_domain_name        = "{s.get('api_domain_name', '')}"
ses_email_from         = "{s.get('ses_email_from', '')}"
ses_verified_domain    = "{s.get('ses_verified_domain', 'breachline.app')}"
pin_request_rate_limit = {s.get('pin_request_rate_limit', 3)}
lambda_memory_size     = {s.get('lambda_memory_size', 512)}
lambda_timeout         = {s.get('lambda_timeout', 30)}
audit_ttl_days         = {s.get('audit_ttl_days', 90)}
pin_ttl_hours          = {s.get('pin_ttl_hours', 12)}
alarm_email            = "{s.get('alarm_email', '')}"
"""
    write(REPO / f"infra/sync-api/{env}.tfvars", body)


def render_payment_api(c: dict, env: str) -> None:
    p = env_component(c, env, "payment_api")
    # stripe_* + license_signing_private_key are sensitive -> secrets.env.
    body = f"""{HEADER}
aws_region       = "{c['aws']['region']}"
environment      = "{env}"
ses_sender_email = "{p.get('ses_sender_email', '')}"
"""
    write(REPO / f"infra/payment-api/{env}.tfvars", body)


def fmt_tfvars() -> None:
    """Align columns in the generated tfvars with `terraform fmt`."""
    proc = subprocess.run(
        ["terraform", "fmt", str(REPO / "infra")],
        capture_output=True, text=True, check=False,
    )
    if proc.returncode != 0:
        # fmt is cosmetic; warn but don't fail the render.
        print(f"[warn] terraform fmt skipped:\n{proc.stderr.strip()}", file=sys.stderr)


def main() -> None:
    if len(sys.argv) != 2 or sys.argv[1] not in ENVIRONMENTS:
        sys.exit(f"usage: render-config.py <{'|'.join(ENVIRONMENTS)}>")
    env = sys.argv[1]
    c = load_config()
    v = load_vault()
    render_secrets_env(c, v, env)
    render_website(c, env)
    render_sync_api(c, env)
    render_payment_api(c, env)
    fmt_tfvars()
    print(f"[ok] rendered {env} config from config.yml + secrets.vault.yml")


if __name__ == "__main__":
    main()
